In [1]:
import numpy as np

In [5]:
a = [1,5.,3.54,6.]

In [6]:
# TO CONVERT LIST INTO ARRAY
a1 = np.array(a)
a1

array([1.  , 5.  , 3.54, 6.  ])

In [7]:
#  to check dimention 
a1.ndim

1

In [8]:
# to check shape of array(column,row)
a1.shape

(4,)

In [9]:
a=np.array([[1,2,3]
            ,[4,5,6]])
type(a)

numpy.ndarray

In [10]:
# to check dimention
a.ndim

2

In [11]:
# to check of array
a.shape

(2, 3)

In [12]:
a.dtype

dtype('int32')

In [13]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [14]:
# a = np.ones(6, )
# a
a1 = np.ones((2,4,4))
a1

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [15]:
a2 = np.ones((3,4,4))
a2

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [16]:
a = np.zeros((2,4,4))
a

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [17]:
np.empty((3,9))

array([[1.29441743e-312, 2.37663529e-312, 2.05833592e-312,
        2.41907520e-312, 2.56761491e-312, 1.93101617e-312,
        1.03977794e-312, 1.06099790e-312, 1.08221785e-312],
       [2.12199580e-313, 6.79038653e-313, 6.79038653e-313,
        6.79038653e-313, 6.79038653e-313, 6.79038653e-313,
        6.79038653e-313, 1.93101617e-312, 9.33678148e-313],
       [9.33678148e-313, 1.97345609e-312, 8.70018275e-313,
        2.46151512e-312, 2.37663529e-312, 8.48798317e-313,
        8.70018275e-313, 1.11260619e-306, 8.91238233e-313]])

In [18]:
R = np.array([1,2,5,6,6,4,8,7,9,4,6,7])
len(R)

12

In [19]:
# TO GET DESIRED NO. OF ARRAY
z=np.arange(1,25)
z

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [20]:
np.linspace(1,5,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [21]:
a=R.reshape(4,3)
a

array([[1, 2, 5],
       [6, 6, 4],
       [8, 7, 9],
       [4, 6, 7]])

In [22]:
R.ravel()

array([1, 2, 5, 6, 6, 4, 8, 7, 9, 4, 6, 7])

In [23]:
a.flatten(order = "F")

array([1, 6, 8, 4, 2, 6, 7, 6, 5, 4, 9, 7])

In [24]:
a.reshape(1,-1)

array([[1, 2, 5, 6, 6, 4, 8, 7, 9, 4, 6, 7]])

In [25]:
import numpy as np

In [26]:
a = np.arange(1,26).reshape(5,5)
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [27]:
b = np.arange(1,26).reshape(5,5)
b

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [28]:
#  to reverse column into row

b.transpose()


array([[ 1,  6, 11, 16, 21],
       [ 2,  7, 12, 17, 22],
       [ 3,  8, 13, 18, 23],
       [ 4,  9, 14, 19, 24],
       [ 5, 10, 15, 20, 25]])

In [29]:
import numpy as np

In [30]:
c=b.reshape(-1,1)
c

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24],
       [25]])

In [31]:
c.reshape(1,-1)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23, 24, 25]])

In [7]:
a= np.arange(1,21).reshape(5,4)
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [8]:
# to get selected data(to crop the image)
a[2:4,2:4]

array([[11, 12],
       [15, 16]])

In [9]:
a=np.arange(1,10).reshape(3,3)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
b=np.arange(1,10).reshape(3,3)
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
# to add matrices
np.add(a,b)

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [12]:
# to subtract the matrices
np.subtract(a,b)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [13]:
# to multiply th matrices
a1=np.multiply(a,b)
a1

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [14]:
# to devide the matrices
np.divide(a,b)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [15]:
a1

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [16]:
# to check minimum no. in matrices row wise(0) and column wise(1)
a1.min(axis = 0)

array([1, 4, 9])

In [17]:
# to check maximum no. in matrices row wise(0) and column wise(1)
a1.max(axis = 1)

array([ 9, 36, 81])

In [22]:
# to add every no. in matrices
np.sum(a1)
# also can find rw=ow wise or column wise
np.sum(a1, axis = 1)

array([ 14,  77, 194])

In [21]:
# to check the index of maximum value
np.argmax(a1)
# also can be find row or column wise
np.argmax(a1, axis = 1)

array([2, 2, 2], dtype=int64)

In [20]:
# to check the index of minimum value
np.argmin(a1)

0

In [25]:
# to get the average value 
np.mean(a1)

31.666666666666668

In [26]:
# median= center value point
np.median(a1)

25.0

In [27]:
# standard deviation
# where maximum value is coming 
np.std(a1)

26.474306202219704

In [28]:
# variance
# is range which is starting point to end point
np.var(a1)

700.8888888888888

In [29]:
# squar root
np.sqrt(a1)

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [30]:
# log
np.log(a1)

array([[0.        , 1.38629436, 2.19722458],
       [2.77258872, 3.21887582, 3.58351894],
       [3.8918203 , 4.15888308, 4.39444915]])

In [35]:
a=np.arange(1,101).reshape(10,10)
a

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [43]:
# slicing operaton and to cut the image(image crop)
# [row:column,row:column]
a[3:6,3:8]

array([[34, 35, 36, 37, 38],
       [44, 45, 46, 47, 48],
       [54, 55, 56, 57, 58]])

In [48]:
a=(1,2,3,5,4)
np.array(a)

array([1, 2, 3, 5, 4])

a = {name:rushi,number:7775928899,city:latur}
np.array(a)

In [50]:
a = {"name":"rushi","number":7775928899,"city":"latur"}
np.array(a)

array({'name': 'rushi', 'number': 7775928899, 'city': 'latur'},
      dtype=object)

In [51]:
a= np.arange(1,10).reshape(3,3)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [52]:
a1= np.arange(1,10).reshape(3,3)
a1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [53]:
# matrix multiplication
# -*|
np.dot(a,a1)

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [58]:
a=np.arange(1,17).reshape(4,4)
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [59]:
b=np.arange(17,33).reshape(4,4)
b

array([[17, 18, 19, 20],
       [21, 22, 23, 24],
       [25, 26, 27, 28],
       [29, 30, 31, 32]])

In [63]:
# to add two matrices in row wise by default if column wise we have to add axis = 1)
np.concatenate((a,b),axis = 1)

array([[ 1,  2,  3,  4, 17, 18, 19, 20],
       [ 5,  6,  7,  8, 21, 22, 23, 24],
       [ 9, 10, 11, 12, 25, 26, 27, 28],
       [13, 14, 15, 16, 29, 30, 31, 32]])

In [66]:
# to add matrices horizontally
np.hstack((a,b))

array([[ 1,  2,  3,  4, 17, 18, 19, 20],
       [ 5,  6,  7,  8, 21, 22, 23, 24],
       [ 9, 10, 11, 12, 25, 26, 27, 28],
       [13, 14, 15, 16, 29, 30, 31, 32]])

In [69]:
# to add matrices vertically
np.vstack((a,b))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24],
       [25, 26, 27, 28],
       [29, 30, 31, 32]])

In [77]:
# split
# (matrix,parts axis)
b = np.split(a,2,axis = 1)
b

[array([[ 1,  2],
        [ 5,  6],
        [ 9, 10],
        [13, 14]]),
 array([[ 3,  4],
        [ 7,  8],
        [11, 12],
        [15, 16]])]

In [78]:
b[0]

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10],
       [13, 14]])

In [81]:
s = np.array([1,2,3,4,5,6,7,468,64,6464,34,14,64,789,122])

In [86]:
np.split(s,[2,6,10])

[array([1, 2]),
 array([3, 4, 5, 6]),
 array([   7,  468,   64, 6464]),
 array([ 34,  14,  64, 789, 122])]

In [91]:
# numpy->random->other functions of random
# we  also can get in 2D or 3D  (dimention,row,column)
np.random.random((2,4,3))

array([[[0.70454819, 0.1629396 , 0.65750596],
        [0.17528416, 0.176051  , 0.92238147],
        [0.9114523 , 0.42394544, 0.01084944],
        [0.17807168, 0.27808434, 0.54119949]],

       [[0.02806567, 0.42807729, 0.05090159],
        [0.68028867, 0.23000986, 0.12355335],
        [0.14322025, 0.31818121, 0.18197802],
        [0.91814929, 0.08049055, 0.34218467]]])

In [104]:
np.random.randint(1,20,size=(3,5,4))

array([[[11, 14,  1,  3],
        [16,  9, 16,  5],
        [ 6,  1,  2, 18],
        [ 9, 16, 16, 15],
        [ 9,  6,  2, 18]],

       [[ 4,  8, 15,  6],
        [14, 19, 15,  5],
        [11, 16,  2,  4],
        [ 2, 15,  9, 19],
        [ 2,  6, 16,  2]],

       [[16,  7,  7, 12],
        [ 5,  9,  2,  7],
        [ 5, 17, 18, 12],
        [ 1, 12, 17, 18],
        [17,  3, 10, 18]]])

In [108]:
a=np.linspace(1,15,25)
a

array([ 1.        ,  1.58333333,  2.16666667,  2.75      ,  3.33333333,
        3.91666667,  4.5       ,  5.08333333,  5.66666667,  6.25      ,
        6.83333333,  7.41666667,  8.        ,  8.58333333,  9.16666667,
        9.75      , 10.33333333, 10.91666667, 11.5       , 12.08333333,
       12.66666667, 13.25      , 13.83333333, 14.41666667, 15.        ])

In [111]:
np.random.choice(a,(2,2))

array([[ 3.91666667,  3.91666667],
       [10.91666667, 12.08333333]])

In [119]:
# permultation 
# this will shuffle the list
np.random.permutation(a)
np.random.choice(a,(4,3))

array([[ 5.08333333,  5.66666667,  3.33333333],
       [ 5.66666667,  2.75      ,  6.83333333],
       [ 5.66666667, 15.        ,  1.58333333],
       [ 6.83333333,  4.5       ,  4.5       ]])

In [123]:
# (mean,std deviation,samples)
np.random.normal(25,5,50)

array([24.3548084 , 25.70279933, 21.25611618, 19.75725431, 15.77716798,
       28.07476146, 24.35564133, 30.00256951, 32.87015794, 25.15990502,
       26.14802549, 29.59475246, 28.57025112, 22.49461779, 11.60157698,
       34.408471  , 30.70019811, 25.82163645, 33.91915216, 28.31032776,
       24.96000061, 34.72765175, 33.98234311, 24.71876327, 24.67864964,
       30.16629514, 23.92769508, 28.06808815, 30.72899617, 19.44825291,
       29.70529551, 22.7971371 , 28.05504296, 27.50075298, 20.45270129,
       24.54534048, 23.79290283, 22.03767104, 25.93993194, 18.59035084,
       34.84184995, 14.63449732, 18.88381579, 37.79287043, 23.91846465,
       17.62609588, 17.82573413, 25.34893474, 27.09410727, 31.61390885])

In [124]:
s= "python"
s1= 'data science'
# in char we can use string function



In [125]:
np.char.add(s,s1)

array('pythondata science', dtype='<U18')

In [127]:
np.char.lower(s)

array('python', dtype='<U6')

In [128]:
np.char.upper(s1)

array('DATA SCIENCE', dtype='<U12')

In [130]:
np.char.center(s,25,"*")

array('**********python*********', dtype='<U25')

In [131]:
np.char.split(s1)

array(list(['data', 'science']), dtype=object)